### ISSUE TITLE
request for documentation on getIdClaims and getAccessClaims functions

### ISSUE THREAD

**Issue by ryanburnette** [therootcompany/auth3000#11]
Can I get some documentation on getIdClaims and getAccessClaims functions? I'd like a better understanding of what they're doing and how errors thrown within them are handled.

**Comment by coolaj86** [comment]
Both are used the same right now:

In all cases you take in the `claims` that you gave as `req.body` and you give back the `claims` that you want to go into the token. The two might be similar, or might not be. It's up to you to decide.

# Scenarios

If you're doing a password sign in, all you get is whatever was in `req.body` and it's up to you to figure out how to validate email or username and password.

```js
getIdClaims({
  claims: req.body, // additional random stuff as sent from the browser (you)
});
```

If it's called after a Google Sign-In, it'll be called after the validation of the Google Token, and look like this, with `claims` being whatever you put in `req.body`:

```js
getIdClaims({
  email: googleEmail,
  iss: "https://accounts.google.com",
  ppid: googlePpid,
  claims: req.body, // additional random stuff as sent from the browser (you)
});
```

If it's called after a cookie token refresh or id token exchange, it'll be called after the current session validation, and look like this, with `jws` be a valid existing session with whatever `claims` were provided previously, and `claims` being whatever you put in `req.body`:

```js
getIdClaims({
  jws: existingValidatedSession,
  claims: req.body, // additional random stuff as sent from the browser (you)
});
```

If it's called after the magic link validation, your site will be `iss` because your site is the one doing the verification, and `claims` being whatever you put in `req.body`:

```js
getIdClaims({
  email: knownEmail,
  iss: "http://localhost:3002", // yourself
  claims: req.body, // additional random stuff as sent from the browser (you)
});
```

**Comment by coolaj86** [comment]
I think we should discuss this.

I don't have a good solution top of mind, but I think if we both looked at it we'd come up with the right thing.

Maybe `getUser` / `getIdClaims` should actually be more like:

- `session.byOidc({ email, iss, ppid, ... })` // google sign in
- `session.byCredentials({ ... })` // password
- `session.byCookie({ jws, ... })` // refresh cookie
- `session.byToken({ jws, ... })` // exchange short-lived token for another token
- `session.byIdentifierVerification({ type, value, ... })` // email magic link / sms code

In any case, there are two (or three) values that need to be set - how long the refresh cookie should last (ex: 30 days) and how long the short-lived token should last (ex: 15m).

```js
{
     id_claims: { exp: '1h', email: 'john@email.com' },
     access_claims: { exp: '15m', account: 'pottytrainers', roles: ["admin"] },
     session_claims: { exp: '30d'  },
}
```

**Comment by coolaj86** [comment]
"Final" example forthcoming. Closing for now.
