### ISSUE TITLE
it's issuing challenge token with empty body

### ISSUE THREAD

**Issue by ryanburnette** [therootcompany/auth3000#17]
Not sure why the body is empty, but on my test app when I post the challenge/issue with an empty body it still issues a token. Probably need some validation there.

**Comment by coolaj86** [comment]
> Probably need some validation there.

You should validate in `notify` and throw an error if what your frontend provides doesn't meet your requirements.

Whatever the data is is opaque to auth3000.

Though agreed there should be something at all... I'll fix that.

**Comment by coolaj86** [comment]
I almost put this in as the default error... but, I think it really is up to the developer to decided how to handle this since, really, they frontend they provided should have already done some sort of validation, and auth3000 doesn't know what that should have been.

```js
    if (!req.body || !req.body.type || !req.body.value) {
      // Should this be a dev-only message?
      // The front-end should have validated this already
      let err = new Error("The email (or phone) fields cannot be left blank.");
      err.status = 400;
      err.code = "INVALID_IDENTIFIER";
      throw err;
    }
```

I'm going to leave this out for now, but I'm moving `notify` to being called first, before even saving the values. `notify` should throw the appropriate error.

**Comment by ryanburnette** [comment]
I wouldn't have thought about validating and throwing errors in notify. That'll work though.
